# Generated by Django 6.0.1 on 2026-02-03 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reshare',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
